package common

var STATUS_OK = "0"
var STATUS_ERROR = "1"
var DATEFORMAT = "2006-01-02 15:04:05"

//批量导入文件名解析规则定义
const FACEFILENAMEPART_NAME = "0"
const FACEFILENAMEPART_CERTNUMBER = "1"
const FACEFILENAMEPART_GENDER = "2"
const FACEFILENAMEPART_CERTTYPE = "3"
const FACEFILENAMEPART_NATIVEPLACE = "4"
const FACEFILENAMEPART_TELEPHONE = "5"
const FACEFILENAMEPART_ADDRESS = "6"
const FACEFILENAMEPART_WORKPLACE = "7"
const FACEFILENAMEPART_COMMENTS = "8"
